import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import ProductPage from "../../src/components/ProductPage";
import { fetchProduct } from "../../src/redux/product/actions";
import { State, wrapper } from "../../src/redux/store";

export default function ProductNextPage() {
  const { data: product } = useSelector((state: State) => state.product);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductPage product={product} />
    </div>
  );
}

ProductNextPage.getInitialProps = wrapper.getInitialPageProps(
  (store) =>
    async ({ query }) => {
      let { id } = query;
      if (Array.isArray(id)) {
        id = id[0];
      }
      const a = await store.dispatch(fetchProduct(id));
      console.log("a", a);
    }
);
